//
//  DetailsPresenter.swift
//  NYTCleanSwift
//
//  Created by Abdulrahman on 4/8/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
//    func presentSomething(response: Details.Something.Response)
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?

    // MARK: Parse and calc respnse from DetailsInteractor and send simple view model to DetailsViewController to be displayed

//    func presentSomething(response: Details.Something.Response) {
//        let viewModel = Details.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
//    }
//
//    func presentSomethingElse(response: Details.SomethingElse.Response) {
//        let viewModel = Details.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
