    //
    //  HomeInteractor.swift
    //  NYTCleanSwift
    //
    //  Created by Abdulrahman on 4/8/22.
    //  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
    //
    //  This file was generated by the Clean Swift Xcode Templates so
    //  you can apply clean architecture to your iOS and Mac projects,
    //  see http://clean-swift.com
    //

import UIKit

protocol HomeBusinessLogic {
    func getArticles(request: Home.GetArticles.Request)
        //    func doSomethingElse(request: Home.SomethingElse.Request)
}

protocol HomeDataStore {
        //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?

        //var name: String = ""

        // MARK: Do something (and send response to HomePresenter)

    func getArticles(request: Home.GetArticles.Request) {

            // fetch data


        NYTService.shared.getArticles(with: NYTService.baseUrlString) {[weak self] result in

            do {
                let resultResponse = try result.get()
                let response = Home.GetArticles.Response(resultResponse: resultResponse)
                self?.presenter?.presentArticles(response: response)
            } catch {
                print(error.localizedDescription)
            }
        }

    }


}

