//
//  HomePresenter.swift
//  NYTCleanSwift
//
//  Created by Abdulrahman on 4/8/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentArticles(response: Home.GetArticles.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    // MARK: Parse and calc respnse from HomeInteractor and send simple view model to HomeViewController to be displayed

    func presentArticles(response: Home.GetArticles.Response) {
        let viewModel = Home.GetArticles.ViewModel(resultResponse: response.resultResponse)
        viewController?.displayArticles(viewModel: viewModel)
    }

}
