//
//  HomeModels.swift
//  NYTCleanSwift
//
//  Created by Abdulrahman on 4/8/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases

    enum GetArticles
    {
        struct Request
        {

        }

        struct Response
        {
            let resultResponse: ResultResponse
        }

        struct ViewModel
        {
            let resultResponse: ResultResponse
        }
    }
}

